lang: en-au
name: Disruption 2020 // Curtin Grad Show
title: Disruption 2020 // Curtin Grad Show
# see https://ogp.me/#types
type: website
url: https://www.curtindesign.com/
image: https://curtindesign.com/video/disrupt.jpg
description: Disruption 2020 is the final year showcase of Curtin University Design graduates.
